# Docker Compose para Mini-Shop con Puerto 8088
# Configuración para evitar conflictos con Nginx existente

version: '3.8'

services:
  # ========================================
  # NATS Server (Message Broker) - Instancia dedicada para Mini-Shop
  # ========================================
  nats-server:
    image: nats:2.10-alpine
    container_name: mini-shop-nats
    ports:
      - "8422:4222"      # NATS Client
      - "8423:8222"      # HTTP Monitoring
      - "8424:6222"      # Cluster Port
    command: 
      - "--http_port"
      - "8222"
      - "--name"
      - "mini-shop-nats-dedicated"
      - "--server_name"
      - "mini-shop-instance"
    volumes:
      - nats_data:/data
    networks:
      - mini-shop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # ========================================
  # Orders Service
  # ========================================
  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    container_name: mini-shop-orders
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - nats-server
    volumes:
      - orders_data:/app/data
    networks:
      - mini-shop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ========================================
  # Products Service
  # ========================================
  products-service:
    build:
      context: ./products-service
      dockerfile: Dockerfile
    container_name: mini-shop-products
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - nats-server
    volumes:
      - products_data:/app/data
    networks:
      - mini-shop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ========================================
  # Notifications Service
  # ========================================
  notifications-service:
    build:
      context: ./notifications-service
      dockerfile: Dockerfile
    container_name: mini-shop-notifications
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - nats-server
    volumes:
      - notifications_data:/app/data
    networks:
      - mini-shop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ========================================
  # Nginx (Reverse Proxy y Load Balancer) - Puerto 8088
  # ========================================
  nginx:
    image: nginx:1.25-alpine
    container_name: mini-shop-nginx
    ports:
      - "8088:8088"      # Puerto 8088 para evitar conflictos
      - "8443:443"       # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - orders-service
      - products-service
      - notifications-service
    networks:
      - mini-shop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

# ========================================
# Networks
# ========================================
networks:
  mini-shop-network:
    driver: bridge
    name: mini-shop-net

# ========================================
# Volumes
# ========================================
volumes:
  nats_data:
    name: mini-shop-nats-data
  orders_data:
    name: mini-shop-orders-data
  products_data:
    name: mini-shop-products-data
  notifications_data:
    name: mini-shop-notifications-data
  nginx_logs:
    name: mini-shop-nginx-logs
