server:
  port: 8081

spring:
  application:
    name: orders-service

  cloud:
    stream:
      default-binder: nats
      binders:
        nats:
          type: nats
          environment:
            spring:
              cloud:
                stream:
                  nats:
                    servers: nats://nats:4222

      bindings:
        orderCreated-out-0:
          destination: order.created
          content-type: application/json
